### PR TITLE
Update step.sh

### PR DESCRIPTION
**Pull request by anasanasanas**
For some reason Huawue app gallery takes some time before finalizing the new version processing casing submission for review to fail, we can mitigate this by waiting some times before submission the new version for review

### CODE REVIEW

**Comment by ferPrieto** [comment]
I will need to test this case again. From my experience the Huawei AppGallery Connect API is a bit inconsistent sometimes when it comes to deployment, I'd avoid to add 30" on top of the whole workflow time, because it seems like a workaround rather than the actual fix.
Anyway thanks for raising the issue and I will keep you posted next week 👍🏽

**Comment by anasanasanas** [comment]
Thanks Bro

**Comment by anasanasanas** [comment]
Hello @ferPrieto, is there are any updates regarding this issue?

**Comment by ferPrieto** [comment]
Tested and reproduced only once of 15 times. Due to the flakiness of the API is not appropriate to add a simple sleep (30"), because it would cause a delay in every single deployment. 

I can't accept the suggested solution. Unless this case was 100% reproduced every single time I wouldn't add that 'workaround'. @anasanasanas

**Pull request closed without merging**
